"""001 - PostgreSQL extensions

Everything this schema needs that is not in core PostgreSQL 16.
See DATA_MODEL.md 1.4 for the full feature/version matrix.

Revision ID: 001
Revises:
Create Date: 2026-09-14

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (extension, why it is needed)
EXTENSIONS: list[tuple[str, str]] = [
    (
        "citext",
        "Case-insensitive business keys: emails, slugs, tail numbers, operator "
        "codes, quote/booking/invoice numbers (DATA_MODEL 1.2).",
    ),
    (
        "ltree",
        "segments.path -- materialized ancestry for the segment hierarchy "
        "(DATA_MODEL 3.2).",
    ),
    (
        "btree_gist",
        "Lets a GiST index handle '=' on uuid, which the EXCLUDE constraint on "
        "aircraft_operator_assignments needs alongside daterange '&&' "
        "(DATA_MODEL 3.3).",
    ),
]

# Deliberately NOT installed:
#
#   pgcrypto / uuid-ossp -- no database-side UUID generation. Identifiers are
#       UUIDv7 generated by the application (DATA_MODEL 1.5), and PG13+ already
#       has gen_random_uuid() in core if a random UUID is ever needed.
#       Column-level encryption is envelope encryption done in the application,
#       so pgcrypto would add an attack surface without adding a capability.
#
#   postgis -- available on Neon but not in the local postgres:16 container.
#       airports.location is a core `point` instead (DATA_MODEL 1.6).


def upgrade() -> None:
    for name, _why in EXTENSIONS:
        op.execute(f'CREATE EXTENSION IF NOT EXISTS "{name}"')


def downgrade() -> None:
    # Reverse order; RESTRICT so we fail loudly rather than cascade-dropping
    # columns that still depend on these types.
    for name, _why in reversed(EXTENSIONS):
        op.execute(f'DROP EXTENSION IF EXISTS "{name}" RESTRICT')
